version: '3.9'
services:
  dev:
    build:
      context: ..
      dockerfile: Dockerfile
    user: developer
    image: bumbag-image
    container_name: bumbag-dev
    command: sleep infinity
    volumes:
      - ..:/code
