name: ci status

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration:

    runs-on: ubuntu-latest

    steps:
    - name: Check-out repository
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.3.1
        virtualenvs-create: false
        installer-parallel: true

    - name: Install bumbag
      run: poetry install

    - name: Run isort
      run: python -m isort --check-only --line-length 88 --profile black ./

    - name: Run Black
      run: python -m black --check --line-length 88 ./

    - name: Run Flake8
      run: python -m flake8 --doctests --max-line-length 88 src/ tests/

    - name: Run pytest doctest
      run: python -m pytest --doctest-modules

    - name: Run pytest
      run: python -m pytest tests/ --cov=bumbag --cov-report=xml

    - name: Use Codecov to track coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml

    - name: Build documentation
      run: make html --directory docs/
